version: '3'

services:
  kleinDocsRunner:
    image: docker.dariusklein.nl/runner:latest
    restart: always
    privileged: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    environment:
      REPO: ${KLEIN_DOCS_REPO}
      TOKEN: ${KLEIN_DOCS_TOKEN}
