name: build and deploy images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-KleinDocs-Runner:

    runs-on: ubuntu-latest
    

    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: docker login docker.dariusklein.nl -u Darius -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: docker build . --tag docker.dariusklein.nl/runner
      - name: Docker push
        run: docker push docker.dariusklein.nl/runner
